// Code generated by mockery v2.53.3. DO NOT EDIT.

package copy

import mock "github.com/stretchr/testify/mock"

// mockDoguConfigReaderWriter is an autogenerated mock type for the doguConfigReaderWriter type
type mockDoguConfigReaderWriter struct {
	mock.Mock
}

type mockDoguConfigReaderWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigReaderWriter) EXPECT() *mockDoguConfigReaderWriter_Expecter {
	return &mockDoguConfigReaderWriter_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: key
func (_m *mockDoguConfigReaderWriter) Exists(key string) (bool, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigReaderWriter_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockDoguConfigReaderWriter_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - key string
func (_e *mockDoguConfigReaderWriter_Expecter) Exists(key interface{}) *mockDoguConfigReaderWriter_Exists_Call {
	return &mockDoguConfigReaderWriter_Exists_Call{Call: _e.mock.On("Exists", key)}
}

func (_c *mockDoguConfigReaderWriter_Exists_Call) Run(run func(key string)) *mockDoguConfigReaderWriter_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguConfigReaderWriter_Exists_Call) Return(_a0 bool, _a1 error) *mockDoguConfigReaderWriter_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigReaderWriter_Exists_Call) RunAndReturn(run func(string) (bool, error)) *mockDoguConfigReaderWriter_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *mockDoguConfigReaderWriter) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigReaderWriter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockDoguConfigReaderWriter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *mockDoguConfigReaderWriter_Expecter) Get(key interface{}) *mockDoguConfigReaderWriter_Get_Call {
	return &mockDoguConfigReaderWriter_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *mockDoguConfigReaderWriter_Get_Call) Run(run func(key string)) *mockDoguConfigReaderWriter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguConfigReaderWriter_Get_Call) Return(_a0 string, _a1 error) *mockDoguConfigReaderWriter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigReaderWriter_Get_Call) RunAndReturn(run func(string) (string, error)) *mockDoguConfigReaderWriter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *mockDoguConfigReaderWriter) Set(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigReaderWriter_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockDoguConfigReaderWriter_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *mockDoguConfigReaderWriter_Expecter) Set(key interface{}, value interface{}) *mockDoguConfigReaderWriter_Set_Call {
	return &mockDoguConfigReaderWriter_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *mockDoguConfigReaderWriter_Set_Call) Run(run func(key string, value string)) *mockDoguConfigReaderWriter_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockDoguConfigReaderWriter_Set_Call) Return(_a0 error) *mockDoguConfigReaderWriter_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigReaderWriter_Set_Call) RunAndReturn(run func(string, string) error) *mockDoguConfigReaderWriter_Set_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguConfigReaderWriter creates a new instance of mockDoguConfigReaderWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguConfigReaderWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguConfigReaderWriter {
	mock := &mockDoguConfigReaderWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
